Workflow CI

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -41,6 +41,7 @@ jobs:
     # Run as a mlflow project
     - name: Run mlflow project
       run: |
+        export MLFLOW_TRACKING_URI=./mlruns
         mlflow run MLproject --env-manager=local
 
     
@@ -51,12 +52,18 @@ jobs:
         FOLDER_PATH=$(ls -td mlruns/0/*/ | grep -v 'models' | head -n 1)
         RUN_ID=$(basename "$FOLDER_PATH")
         
+        if [ -z "$RUN_ID" ]; then
+          echo "ERROR: Folder Run ID tidak ditemukan di mlruns/0/"
+          exit 1
+        fi
+
         echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
         echo "Latest run_id yang ditemukan: $RUN_ID"
 
     - name: Build Docker Model
       run: |
-        mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"
+        export MLFLOW_TRACKING_URI=./mlruns
+        mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "cc" --env-manager=local
 
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
