Workflow CI

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -12,6 +12,8 @@ permissions:
 env:
   CSV_URL: "MLproject/heart_preprocessing/heart_preprocessing.csv"
   TARGET_VAR: "Heart Failure Prediction"
+  MLFLOW_ALLOW_FILE_STORE: "true"
+  MLFLOW_TRACKING_URI: "./mlruns"
 
 jobs:
   train-model:
@@ -55,13 +57,21 @@ jobs:
     # Mendapatkan Run ID
     - name: Get Run ID
       run: |
-        RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
+        PATH_TERDALAM=$(ls -td mlruns/0/models/m-*/ | head -n 1)
+        FOLDER_NAME=$(basename "$PATH_TERDALAM")
+        RUN_ID=${FOLDER_NAME#m-}
+        
+        if [ -z "$RUN_ID" ]; then
+          echo "ERROR: Run ID tidak ditemukan!"
+          exit 1
+        fi
+
         echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
         echo "Latest run_id: $RUN_ID"
 
     - name: Build Docker Model
       run: |
-        mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"
+        mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "cc" --env-manager=local
 
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
